name: build

on:
  push:
    branches:
      - '**'

env:
  DOTNET_NOLOGO: true # https://github.com/actions/setup-dotnet#environment-variables-to-use-with-dotnet

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj','**/*.props') }}

      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8
            10
          dotnet-quality: ga

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Codecov test results
        if: github.event_name != 'merge_group' && !cancelled()
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          report_type: test_results
          fail_ci_if_error: true

      - name: Codecov coverage results
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          files: '**/TestResults/*/*.cobertura.xml'
          fail_ci_if_error: true

  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Important for changelog
          # doesn't work with git-cliff
          # https://github.com/orhun/git-cliff/issues/1521
          # filter: blob:none
          show-progress: false

      - name: Generate changelog with git-cliff
        uses: orhun/git-cliff-action@3d96a18cc4ec17e9dc69ddcc424ccafaf1f78ce2 # v4.9.0
        with:
          args: --unreleased --strip all
        env:
          # DEBUG: true
          OUTPUT: CHANGELOG.md

      - name: Adding changelog to summary
        run: cat CHANGELOG.md >> $GITHUB_STEP_SUMMARY
